[workspace]
members = [
    "crates/engine_core",
    "crates/luau_runtime",
    "crates/luau_classes",
    "crates/services",
    "crates/editor_core",
    "crates/editor_ui",
    "crates/editor_bin",
    "crates/editor_parser",
    "crates/launcher_bin",
    "crates/launcher_ui",
    "crates/launcher_core",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Alienudck"]

[workspace.dependencies]
bevy = { version = "0.19", features = ["jpeg", "debug"] }
mlua = { version = "0.11.6", features = ["luau"] }
log = "0.4"
avian3d = { version = "0.7" }
crossbeam-channel = "0.5.15"
num_enum = "0.7.6"
strum = "0.28.0"
strum_macros = "0.28.0"
bevy-tnua = { version = "0.32" }
bevy-tnua-avian3d = { version = "0.12" }
reqwest = "0.13.4"
self-replace = "1.5.0"
directories = "6.0.0"
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
rfd = "0.17.2"

engine_core = { path = "crates/engine_core" }
luau_runtime = { path = "crates/luau_runtime" }
luau_classes = { path = "crates/luau_classes" }
services = { path = "crates/services" }
launcher_ui = { path = "crates/launcher_ui"}
launcher_bin = { path = "crates/launcher_bin"}
launcher_core = { path = "crates/launcher_core"}

[package]
name = "Luau_engine"
version.workspace = true
edition.workspace = true

[[bin]]
name = "luau_engine"
path = "src/main.rs"

[dependencies]
engine_core = { workspace = true }
luau_runtime = { workspace = true }
luau_classes = { workspace = true }
services = { workspace = true }
bevy = { workspace = true }
mlua = { workspace = true }
log = { workspace = true }
avian3d = { workspace = true }
crossbeam-channel = { workspace = true }
bevy-tnua = { workspace = true }
bevy-tnua-avian3d = { workspace = true }
# rfd = { workspace = true }
# bevy_egui = { workspace = true }
# reqwest = { workspace = true }
# self-replace = { workspace = true }
# directories = { workspace = true }
# serde = { workspace = true }
# tokio = { workspace = true }
# serde_json = { workspace = true }
# egui_extras = { workspace = true }
