[package]
name    = "luau_classes"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
mlua = { workspace = true }
luau_runtime = { workspace = true }
log = { workspace = true }
engine_core = { workspace = true }
avian3d = { workspace = true }
num_enum = { workspace = true }
strum = { workspace = true}
strum_macros = { workspace = true}
